const fs = require('fs/promises');
const path = require('path');
const os = require('os');

describe('File Structure Creation from AI Response', () => {
  let testProjectDir;
  
  beforeEach(async () => {
    // Create temporary test directory
    testProjectDir = await fs.mkdtemp(path.join(os.tmpdir(), 'file-structure-test-'));
  });

  afterEach(async () => {
    // Clean up test directory
    try {
      await fs.rm(testProjectDir, { recursive: true, force: true });
    } catch (error) {
      console.warn('Failed to clean up test directory:', error.message);
    }
  });

  // Utility function to ensure directory exists
  async function ensureDir(dir) {
    await fs.mkdir(dir, { recursive: true });
  }

  // Main function to create files from structure (based on Guide.md)
  async function createFilesFromStructure(projectDir, validated) {
    const base = projectDir;
    for (const [section, files] of Object.entries(validated)) {
      for (const filePath of Object.keys(files)) {
        const full = path.join(base, filePath);
        await ensureDir(path.dirname(full));
        const placeholder = `<!-- FILE GENERATED BY STRUCTURE STAGE -->\n/* purpose: ${files[filePath]} */\n`;
        await fs.writeFile(full, placeholder, { flag: 'w' });
      }
    }
  }

  // Utility to check if file exists
  async function fileExists(filePath) {
    try {
      await fs.access(filePath);
      return true;
    } catch {
      return false;
    }
  }

  describe('Frontend Project Structure Creation', () => {
    it('should create Svelte frontend structure correctly', async () => {
      // Simulate AI response for a Svelte frontend project
      const mockValidatedStructure = {
        "frontend": {
          "src/app.html": "Main HTML template for SvelteKit application",
          "src/app.css": "Global CSS styles for the application",
          "src/routes/+layout.svelte": "Root layout component",
          "src/routes/+page.svelte": "Home page component",
          "src/routes/about/+page.svelte": "About page component",
          "src/lib/components/Header.svelte": "Header navigation component",
          "src/lib/components/Footer.svelte": "Footer component",
          "src/lib/stores/user.js": "User state management store",
          "src/lib/utils/api.js": "API utility functions"
        },
        "config": {
          "package.json": "NPM package configuration",
          "svelte.config.js": "SvelteKit configuration",
          "vite.config.js": "Vite build configuration",
          "tailwind.config.js": "Tailwind CSS configuration"
        }
      };

      // Create files from structure
      await createFilesFromStructure(testProjectDir, mockValidatedStructure);

      // Verify frontend files were created
      const frontendFiles = [
        'src/app.html',
        'src/app.css', 
        'src/routes/+layout.svelte',
        'src/routes/+page.svelte',
        'src/routes/about/+page.svelte',
        'src/lib/components/Header.svelte',
        'src/lib/components/Footer.svelte',
        'src/lib/stores/user.js',
        'src/lib/utils/api.js'
      ];

      for (const file of frontendFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
        
        // Verify file content includes placeholder
        const content = await fs.readFile(fullPath, 'utf8');
        expect(content).toContain('FILE GENERATED BY STRUCTURE STAGE');
        expect(content).toContain('purpose:');
      }

      // Verify config files were created
      const configFiles = ['package.json', 'svelte.config.js', 'vite.config.js', 'tailwind.config.js'];
      for (const file of configFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
      }
    });

    it('should handle nested component directories', async () => {
      const mockStructure = {
        "components": {
          "src/lib/components/ui/Button.svelte": "Reusable button component",
          "src/lib/components/ui/Modal.svelte": "Modal dialog component", 
          "src/lib/components/forms/ContactForm.svelte": "Contact form component",
          "src/lib/components/forms/LoginForm.svelte": "User login form",
          "src/lib/components/layout/Sidebar.svelte": "Navigation sidebar",
          "src/lib/components/layout/TopBar.svelte": "Top navigation bar"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // Verify nested directories were created
      const nestedFiles = [
        'src/lib/components/ui/Button.svelte',
        'src/lib/components/ui/Modal.svelte',
        'src/lib/components/forms/ContactForm.svelte', 
        'src/lib/components/forms/LoginForm.svelte',
        'src/lib/components/layout/Sidebar.svelte',
        'src/lib/components/layout/TopBar.svelte'
      ];

      for (const file of nestedFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
      }
    });
  });

  describe('Backend Project Structure Creation', () => {
    it('should create Node.js/Fastify backend structure correctly', async () => {
      const mockValidatedStructure = {
        "backend": {
          "server/app.js": "Main Fastify application entry point",
          "server/routes/auth.js": "Authentication routes",
          "server/routes/users.js": "User management routes", 
          "server/routes/projects.js": "Project CRUD routes",
          "server/services/auth.js": "Authentication service logic",
          "server/services/database.js": "Database connection and utilities",
          "server/models/User.js": "User data model",
          "server/models/Project.js": "Project data model",
          "server/middleware/auth.js": "Authentication middleware",
          "server/utils/validation.js": "Input validation utilities"
        },
        "config": {
          "server/package.json": "Backend package configuration",
          "server/.env.example": "Environment variables template",
          "server/.gitignore": "Git ignore rules for backend"
        }
      };

      await createFilesFromStructure(testProjectDir, mockValidatedStructure);

      // Verify backend structure
      const backendFiles = [
        'server/app.js',
        'server/routes/auth.js',
        'server/routes/users.js',
        'server/routes/projects.js',
        'server/services/auth.js',
        'server/services/database.js',
        'server/models/User.js',
        'server/models/Project.js',
        'server/middleware/auth.js',
        'server/utils/validation.js'
      ];

      for (const file of backendFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
        
        const content = await fs.readFile(fullPath, 'utf8');
        expect(content).toContain('FILE GENERATED BY STRUCTURE STAGE');
      }
    });

    it('should create database and API structure', async () => {
      const mockStructure = {
        "database": {
          "server/db/migrations/001_create_users.sql": "User table migration",
          "server/db/migrations/002_create_projects.sql": "Project table migration",
          "server/db/seeds/users.js": "User seed data",
          "server/db/config.js": "Database configuration"
        },
        "api": {
          "server/api/v1/auth/login.js": "Login endpoint",
          "server/api/v1/auth/register.js": "Registration endpoint",
          "server/api/v1/users/profile.js": "User profile endpoint",
          "server/api/v1/projects/list.js": "Project listing endpoint"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // Verify database files
      expect(await fileExists(path.join(testProjectDir, 'server/db/migrations/001_create_users.sql'))).toBe(true);
      expect(await fileExists(path.join(testProjectDir, 'server/db/migrations/002_create_projects.sql'))).toBe(true);
      
      // Verify API structure
      expect(await fileExists(path.join(testProjectDir, 'server/api/v1/auth/login.js'))).toBe(true);
      expect(await fileExists(path.join(testProjectDir, 'server/api/v1/users/profile.js'))).toBe(true);
    });
  });

  describe('Full-Stack Project Structure Creation', () => {
    it('should create complete full-stack application structure', async () => {
      const mockValidatedStructure = {
        "frontend": {
          "client/src/routes/+page.svelte": "Frontend home page",
          "client/src/lib/api/auth.js": "Frontend auth API client",
          "client/package.json": "Frontend dependencies"
        },
        "backend": {
          "server/app.js": "Backend application entry",
          "server/routes/api.js": "API routes",
          "server/package.json": "Backend dependencies"
        },
        "shared": {
          "shared/types/User.js": "Shared user type definitions",
          "shared/utils/validation.js": "Shared validation utilities"
        },
        "infrastructure": {
          "docker-compose.yml": "Docker services configuration",
          "Dockerfile.frontend": "Frontend container definition",
          "Dockerfile.backend": "Backend container definition"
        },
        "root": {
          "README.md": "Project documentation",
          "package.json": "Root package configuration",
          ".gitignore": "Git ignore rules"
        }
      };

      await createFilesFromStructure(testProjectDir, mockValidatedStructure);

      // Verify all sections were created
      const allFiles = [
        // Frontend
        'client/src/routes/+page.svelte',
        'client/src/lib/api/auth.js',
        'client/package.json',
        // Backend  
        'server/app.js',
        'server/routes/api.js',
        'server/package.json',
        // Shared
        'shared/types/User.js',
        'shared/utils/validation.js',
        // Infrastructure
        'docker-compose.yml',
        'Dockerfile.frontend', 
        'Dockerfile.backend',
        // Root
        'README.md',
        'package.json',
        '.gitignore'
      ];

      for (const file of allFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
      }
    });
  });

  describe('Edge Cases and Error Handling', () => {
    it('should handle empty structure sections gracefully', async () => {
      const mockStructure = {
        "frontend": {},
        "backend": {
          "server/app.js": "Main application file"
        },
        "empty_section": {}
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // Should only create the backend file
      expect(await fileExists(path.join(testProjectDir, 'server/app.js'))).toBe(true);
    });

    it('should handle special characters in file names safely', async () => {
      const mockStructure = {
        "special": {
          "src/components/User-Profile.svelte": "User profile with dash",
          "src/utils/api_client.js": "API client with underscore",
          "src/pages/[id].svelte": "Dynamic route with brackets",
          "src/assets/logo@2x.png": "Retina logo with @ symbol"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      const specialFiles = [
        'src/components/User-Profile.svelte',
        'src/utils/api_client.js', 
        'src/pages/[id].svelte',
        'src/assets/logo@2x.png'
      ];

      for (const file of specialFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
      }
    });

    it('should overwrite existing files with new placeholder content', async () => {
      // Create initial file
      const filePath = path.join(testProjectDir, 'test.js');
      await ensureDir(path.dirname(filePath));
      await fs.writeFile(filePath, 'original content');

      const mockStructure = {
        "test": {
          "test.js": "Updated test file"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // Verify file was overwritten
      const content = await fs.readFile(filePath, 'utf8');
      expect(content).toContain('FILE GENERATED BY STRUCTURE STAGE');
      expect(content).toContain('Updated test file');
      expect(content).not.toContain('original content');
    });

    it('should handle deeply nested directory structures', async () => {
      const mockStructure = {
        "deep": {
          "src/lib/components/forms/inputs/text/TextInput.svelte": "Deep nested text input",
          "src/lib/services/api/v1/auth/providers/oauth/google.js": "Very deep OAuth service",
          "config/environments/production/database/migrations/001_initial.sql": "Deep config file"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      const deepFiles = [
        'src/lib/components/forms/inputs/text/TextInput.svelte',
        'src/lib/services/api/v1/auth/providers/oauth/google.js',
        'config/environments/production/database/migrations/001_initial.sql'
      ];

      for (const file of deepFiles) {
        const fullPath = path.join(testProjectDir, file);
        expect(await fileExists(fullPath)).toBe(true);
      }
    });
  });

  describe('File Content Validation', () => {
    it('should include correct placeholder content in all files', async () => {
      const mockStructure = {
        "test": {
          "component.svelte": "Svelte component for testing",
          "service.js": "Service layer for business logic",
          "config.json": "Configuration file"
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // Check each file has correct content
      const files = [
        { path: 'component.svelte', purpose: 'Svelte component for testing' },
        { path: 'service.js', purpose: 'Service layer for business logic' },
        { path: 'config.json', purpose: 'Configuration file' }
      ];

      for (const file of files) {
        const fullPath = path.join(testProjectDir, file.path);
        const content = await fs.readFile(fullPath, 'utf8');
        
        expect(content).toContain('<!-- FILE GENERATED BY STRUCTURE STAGE -->');
        expect(content).toContain(`/* purpose: ${file.purpose} */`);
      }
    });

    it('should handle files with no purpose description', async () => {
      const mockStructure = {
        "test": {
          "no-purpose.js": "",
          "empty-purpose.js": null,
          "undefined-purpose.js": undefined
        }
      };

      await createFilesFromStructure(testProjectDir, mockStructure);

      // All files should be created even with empty purposes
      expect(await fileExists(path.join(testProjectDir, 'no-purpose.js'))).toBe(true);
      expect(await fileExists(path.join(testProjectDir, 'empty-purpose.js'))).toBe(true);
      expect(await fileExists(path.join(testProjectDir, 'undefined-purpose.js'))).toBe(true);
    });
  });

  describe('Real-World AI Response Simulation', () => {
    it('should handle typical GPT-4o file structure response', async () => {
      // Simulate realistic AI response for a task management app
      const mockGPT4oResponse = {
        "frontend_components": {
          "src/lib/components/TaskCard.svelte": "Individual task display component with edit/delete actions",
          "src/lib/components/TaskList.svelte": "List container for multiple tasks with filtering",
          "src/lib/components/AddTaskForm.svelte": "Form component for creating new tasks",
          "src/lib/components/TaskFilter.svelte": "Filter controls for task status and priority"
        },
        "frontend_pages": {
          "src/routes/+page.svelte": "Main dashboard showing task overview and quick actions",
          "src/routes/tasks/+page.svelte": "Full task management page with all features",
          "src/routes/tasks/[id]/+page.svelte": "Individual task detail and edit page",
          "src/routes/settings/+page.svelte": "User preferences and app configuration"
        },
        "frontend_stores": {
          "src/lib/stores/tasks.js": "Svelte store for task state management and CRUD operations",
          "src/lib/stores/user.js": "User authentication and profile state",
          "src/lib/stores/filters.js": "Task filtering and sorting preferences"
        },
        "backend_routes": {
          "server/routes/tasks.js": "RESTful API endpoints for task CRUD operations",
          "server/routes/auth.js": "User authentication and session management routes",
          "server/routes/users.js": "User profile and preferences management"
        },
        "backend_services": {
          "server/services/taskService.js": "Business logic for task operations and validation",
          "server/services/authService.js": "Authentication logic and JWT token management",
          "server/services/emailService.js": "Email notifications for task reminders"
        },
        "database": {
          "server/models/Task.js": "Task data model with validation and relationships",
          "server/models/User.js": "User model with authentication fields",
          "server/db/migrations/001_create_tasks.sql": "Database migration for tasks table",
          "server/db/migrations/002_create_users.sql": "Database migration for users table"
        }
      };

      await createFilesFromStructure(testProjectDir, mockGPT4oResponse);

      // Verify comprehensive structure creation
      const criticalFiles = [
        'src/lib/components/TaskCard.svelte',
        'src/routes/+page.svelte',
        'src/lib/stores/tasks.js',
        'server/routes/tasks.js',
        'server/services/taskService.js',
        'server/models/Task.js'
      ];

      for (const file of criticalFiles) {
        expect(await fileExists(path.join(testProjectDir, file))).toBe(true);
      }
    });

    it('should handle Claude 3.5 Haiku validated structure response', async () => {
      // Simulate Claude's validation and correction of structure
      const mockClaudeValidated = {
        "corrected_frontend": {
          "src/app.html": "SvelteKit app template with proper meta tags and structure",
          "src/routes/+layout.svelte": "Root layout with navigation and error boundaries",
          "src/lib/components/ui/index.js": "Barrel export for UI components"
        },
        "corrected_backend": {
          "server/app.js": "Fastify app with proper plugin registration and error handling",
          "server/plugins/cors.js": "CORS configuration plugin for cross-origin requests",
          "server/plugins/helmet.js": "Security headers plugin for production safety"
        },
        "added_config": {
          "eslint.config.js": "ESLint configuration for code quality",
          "prettier.config.js": "Prettier formatting rules",
          ".env.example": "Environment variables template with all required keys"
        },
        "added_tests": {
          "src/lib/components/__tests__/ui.test.js": "Component unit tests",
          "server/test/routes/api.test.js": "API endpoint integration tests",
          "test/e2e/user-flow.test.js": "End-to-end user journey tests"
        }
      };

      await createFilesFromStructure(testProjectDir, mockClaudeValidated);

      // Verify Claude's corrections were applied
      const validatedFiles = [
        'src/app.html',
        'server/plugins/cors.js',
        'eslint.config.js',
        'src/lib/components/__tests__/ui.test.js'
      ];

      for (const file of validatedFiles) {
        expect(await fileExists(path.join(testProjectDir, file))).toBe(true);
      }
    });
  });
});